# CONSTANT VALUES

WIDTH: int = 1920
HEIGHT: int = 1080
FPS: int = 60
PLAYER_START_X: int = int(WIDTH / 2) - 40
PLAYER_START_Y: int = int(HEIGHT / 2) - 10
PLAYER_SIZE: float = 0.3
PLAYER_SPEED: int = 10
PLAYER_SHOOT_COOLDOWN: int = 20
BOX_BOUNDARY_TOP: int = int(WIDTH / 2)
PLAYER_BOUNDARY_Y: int = int(HEIGHT / 2)
ROTATE_SPEED: int = 5
CIRCLE_RADIUS: int = 2
ENEMY_DELAY = 50


ENEMY_COUNT: int = 50
ENEMY_SHOOT_COOLDOWN = 100

BULLET_SCALE: float = 0.2
BULLET_SPEED: float = 50.0
BULLET_LIFETIME: int = 1500 #ms