# CONSTANT VALUES

WIDTH: int = 1920
HEIGHT: int = 1080
FPS: int = 60
PLAYER_START_X: int = int(WIDTH / 2) - 100
PLAYER_START_Y: int = int(HEIGHT / 2) - 50
PLAYER_SIZE: float = 0.5
PLAYER_SPEED: int = 10
BOX_BOUNDARY_TOP: int = int(WIDTH / 2)
PLAYER_BOUNDARY_Y: int = int(HEIGHT / 2)
